### ISSUE TITLE
Function 'fromList' in module Data.Stream.Infinite.Skew causes program to hang.

### ISSUE THREAD

**Issue by danidiaz** [ekmett/streams#2]
In module **Data.Stream.Infinite.Skew**, there are two ways to create Streams: **fromList** and **tabulate**. tabulate works ok, but I'm having problems with fromList:

    import qualified Data.Stream.Infinite.Skew as S
  
    head1 :: Int
    head1 = S.head $ S.tabulate (([1..]!!) . fromIntegral)
  
    head2 :: Int
    head2 = S.head $ S.fromList [1..]
  
    main :: IO ()
    main = do
        putStrLn (show head1) -- works ok
        putStrLn (show head2) -- hangs the program

I'm using ghc 7.6.2.

**Comment by ekmett** [comment]
Removed.
