### ISSUE TITLE
Turn comments in Data.Stream.Infinite.Skew into Haddock comments.

### ISSUE THREAD

**Issue by danidiaz** [ekmett/streams#3]
In the source code for module **Data.Stream.Infinite.Skew**, the functions **dropWhile**, **span**, **break**, **split**, **splitW**, **insert**, **insertBy** and **adust** have associated comments which could be turned into Haddock documentation.

( I would have submitted a pull request with the changes, but I'm not sure that the complexity given for **split** is correct in the comment. Perhaps it should be something like **min(O(n), O(log n))** instead of  **(O(n), O(log n))** ?)

**Comment by ekmett** [comment]
Fixed.

The `(O(n), O(log n))` bit is referring to the cost of computing each of the parts of the result. The prefix list is `O(n)` to finish computing and the tail is `O(log n)`.
