### ISSUE TITLE
Data.Stream.Infinite.Skew's 'update' function not working for some indexes.

### ISSUE THREAD

**Issue by danidiaz** [ekmett/streams#4]
Consider the code:

    import Data.Foldable
    import qualified Data.Stream.Infinite.Skew as S

    main :: IO ()
    main = do
        let numbers = S.tabulate id
             numbers' = S.update 14 7777 numbers
        putStrLn $ show $ take 20 $ toList $ numbers'

The 7777 is nowere to be seen in the result, which is:

    [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

The behaviour is also wrong when using 15 as the index. It works correctly when the index is 13 or 16.

**Comment by ekmett** [comment]
Fixed. Thanks!
