### ISSUE TITLE
Data.Stream.Infinite.Functional.Zipper reexports Prelude.reverse

### ISSUE THREAD

**Issue by ndmitchell** [ekmett/streams#9]
The module `Data.Stream.Infinite.Functional.Zipper` contains a load of functions for working on `Zipper`, plus the list-based Prelude function `reverse`. That seems odd - did you forget to restrict the export list (as I'm guessing infinite things don't actually support reverse).

**Comment by ekmett** [comment]
Fixed. Thanks!
